/*
 * File: app/controller/AppLaunchCtrl.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HRApp.controller.mainController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'tabPanel',
            selector: '#tabPanel'
        }
    ],

    
    
    createTab:function(view,record){
    	//alert("db"); alert("len="+record.get('rid'));
    	var leaf=record.get('leaf');
    	if(leaf){
    		var rid=record.get('rid');
			var text=record.get('text');
			var url=record.get('url');
			var tab = Ext.get('tab_'+rid);
			if(tab==null){
				 var subTabPanel=new Ext.Panel({  
					id:'tab_'+rid,  
					title:text,  
					closable:true,  
					html:'<iframe id="iframe_'+rid+'" name="iframe_'+rid+'" scrolling="auto" frameborder="0" width="100%" height="100%" src="'+url+'"></iframe>'  
				 });
				 this.getTabPanel().add(subTabPanel);
				 this.getTabPanel().setActiveTab("tab_"+rid);//.setActive(true);
			}else{  
				 this.getTabPanel().setActiveTab("tab_"+rid);//.setActiveTab("tab_"+rid);//如果已经存在 则激活它  
			}
    	}
    },

    init: function() {
        this.control({
          "#menuPanel":{
            	itemclick:this.createTab//function(view,record){alert("ct");alert("dd"); alert("len="+record.get('rid'));}
            }
        });

    }

});
