/*
 * File: app/view/MyViewport.js
 * 
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 * 
 * This file requires use of the Ext JS 4.0.x library, under independent
 * license. License of Sencha Architect does not include license for Ext JS
 * 4.0.x. For more details see http://www.sencha.com/license or contact
 * license@sencha.com.
 * 
 * This file will be auto-generated each and everytime you save your project.
 * 
 * Do NOT hand edit this file.
 */

Ext.define('HRApp.view.Viewport', {
	extend : 'Ext.container.Viewport',
	renderTo: Ext.getBody(),
	layout : {
		type : 'border'
	},

	initComponent : function() {
		var me = this;

		Ext.applyIf(me, {
			items : [{
						xtype : 'panel',
						height : 72,
						padding : 0,
						layout : {
							align : 'stretch',
							padding : 0,
							type : 'hbox'
						},
						bodyPadding : 0,
						region : 'north',
						dockedItems : [{
									xtype : 'image',
									height : 73,
									width : 201,
									src : 'images/logo.png',
									dock : 'left'
								}, {
									xtype : 'label',
									height : 73,
									html : '<h1>演示</h1>',
									padding : '25 auto 20 30',//上右下左
									text : '',
									flex : 1,
									dock : 'top',
									weight : 10
								}]
					}, {
						xtype : 'tabpanel',
						itemId : 'tabPanel',
						activeTab : 0,
						region : 'center'
					}, {
						xtype : 'treepanel',
						region : 'west',
						split : true,
						itemId : 'menuPanel',
						width : 231,
						//layout:'accordion',
						collapsible:true,
						autoScroll:true,
						title : '导航菜单',
						store :'MenuStore1',
						defaults:{autoScroll:true,border:false},
			            layoutConfig:{
			                animate:true
			            }
			           /* ,listeners:{'itemclick':function(view,record){
			            	alert("dd"); alert("len="+record.get('rid'));
			            	var leaf=record.get('leaf');
			            	if(leaf){
			            		var rid=record.get('rid');
			            		var text=record.get('text');alert('text='+text);
			            		
			            		//createTab();
			            		var tab = Ext.get('tab_'+rid);  
						         //e.stopEvent();//停止事件传递 否则会促使浏览器发送URL（菜单链接）向服务器发送请求  
						         
						            if(tab == null){  
						               // alert(node.attributes.href);  
						                var subTabPanel = new Ext.Panel({  
						                  id:'tab_'+rid,  
						                  title:text,  
						                  closable:true,  
						                  html:'<iframe id="iframe_'+rid+'" name="iframe_'+rid+'" scrolling="auto" frameborder="0" width="100%" height="100%" src="http://www.baidu.com"></iframe>'  
						                });  
						                Ext.widget('tabPanel').add(subTabPanel);//添加该panel  
						                Ext.widget('tabPanel').setActive(true);//激活它  
						                  
						            }else{  
						                Ext.widget('tabPanel').setActive(true);//.setActiveTab("tab_"+rid);//如果已经存在 则激活它  
						            }  
						              
						          //
			            	}
			            }}*/
						,viewConfig : {
							itemId : 'treeMenu'
						}
					}]
		});

		me.callParent(arguments);
	}
	
});